### ISSUE TITLE
Fix trend responsive design

### ISSUE THREAD

**Issue by Exouxas** [USN-Gjengen/APP2000_Gruppe06_Solvann-Driftsystem#74]
When window is small it breaks:
![image](https://github.com/USN-Gjengen/APP2000_Gruppe06_Solvann-Driftsystem/assets/26272249/5b2a745c-bf12-4971-a9a8-63c46084d375)

Works normal when big:
![image](https://github.com/USN-Gjengen/APP2000_Gruppe06_Solvann-Driftsystem/assets/26272249/4bce142e-2d4c-4dd7-bf5f-c665686d1fc3)

**Comment by Mrtacocat** [comment]
LGTM
